version: '3'
services:
    recimed_mysql_db:
        image: mysql:latest
        container_name: mysql_db_rec
        deploy:
        environment:
        - MYSQL_ROOT_PASSWORD=root
        ports:
        - 33060:3306
    web:
        build:
            context: .
            dockerfile: docker/apache/Dockerfile
            args:
                uid: ${UID}
        environment:
            - APACHE_RUN_USER=#${UID}
            - APACHE_RUN_GROUP=#${UID}
        restart: unless-stopped
        volumes: 
            - ./src:/var/www/html
            - ./apache_log:/var/log/apache2
        ports:
            - 80:80
        depends_on: 
            - recimed_mysql_db
        links:
            - recimed_mysql_db
    adminer:
        image: adminer
        restart: unless-stopped
        ports:
            - 8080:8080
    phpmyadmin:
        image: phpmyadmin:latest
        restart: always
        ports:
            - 9001:80
        environment:
            - PMA_ARBITRARY=1        
volumes:
    db_data:
    src: